<?php

/**
 * @file
 * Contains kalaconfig.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function kalaconfig_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the kalaconfig module.
    case 'help.page.kalaconfig':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a base set of configuration and module dependencies for starting new Drupal projects. After installing this module once, you may uninstall it but do not remove it, as composer dependencies are still needed.') . '</p>';
      return $output;

    default:
  }
}
