name: Kalamuna Configuration
type: module
description: Provides a base set of configuration and module dependencies for starting new Drupal projects. After installing this module once, you may uninstall it but do not remove it, as composer dependencies are still needed.
core: 8.x
package: Kalamuna
dependencies:
  - admin_toolbar_tools
  - config_split
  - pathauto
  - redirect
