name: Kalamuna Configuration
type: module
description: Provides a base set of configuration and module dependencies for starting new Drupal projects.
core: 8.x
package: Kalamuna
dependencies:
  - admin_toolbar_tools
  - autogrow_textarea
  - big_pipe
  - chosen
  - components
  - config_direct_save
  - config_split
  - kalastatic
  - linkit
  - pathauto
  - redirect
  - twig_tweak
